name: dino
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2023.01.10
  - certifi=2021.5.30
  - cudatoolkit=11.0.221
  - dataclasses=0.8
  - freetype=2.12.1
  - giflib=5.2.1
  - intel-openmp=2022.1.0
  - jpeg=9b
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuv=1.44.2
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1t
  - pillow=8.3.1
  - pip=21.2.2
  - python=3.6.13
  - pytorch=1.7.1
  - readline=8.2
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - torchvision=0.8.2
  - typing_extensions=4.1.1
  - wheel=0.37.1
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.4.9
  - pip:
      - addict==2.4.0
      - attrs==22.2.0
      - blobfile==0.11.0
      - charset-normalizer==2.0.12
      - cloudpickle==2.2.1
      - dall-e==0.1
      - einops==0.4.1
      - faiss-gpu==1.6.1
      - filelock==3.4.1
      - idna==3.4
      - importlib-metadata==4.8.3
      - importlib-resources==5.4.0
      - iniconfig==1.1.1
      - joblib==1.1.1
      - lmdb==1.4.1
      - mmcv-full==1.3.9
      - munkres==1.1.4
      - mypy==0.971
      - mypy-extensions==1.0.0
      - opencv-python==4.7.0.72
      - packaging==21.3
      - pluggy==1.0.0
      - protobuf==3.19.6
      - py==1.11.0
      - pyarrow==2.0.0
      - pycryptodomex==3.18.0
      - pydevd-pycharm==223.8836.43
      - pyparsing==3.0.9
      - pytest==7.0.1
      - pytest-runner==5.3.2
      - pyyaml==6.0
      - requests==2.27.1
      - scikit-learn==0.24.2
      - scipy==1.5.4
      - sklearn==0.0.post5
      - submitit==1.4.5
      - tensorboardx==2.6
      - threadpoolctl==3.1.0
      - timm==0.3.4
      - tomli==1.2.3
      - tqdm==4.64.1
      - typed-ast==1.5.4
      - urllib3==1.26.16
      - xmltodict==0.12.0
      - yapf==0.32.0
      - zipp==3.6.0
